from __future__ import annotations

import os

from experiment_contract import env_float, env_int
from experiment_contract import env_bool


REWARD_FAMILY_NONE = "none"
REWARD_FAMILY_RSRP = "rsrp"
REWARD_FAMILY_LEGACY_LABEL_SHAPED = "legacy_label_shaped"
REWARD_FAMILY_OUTCOME = "outcome"
OUTCOME_REWARD_PROFILE_V1 = "outcome_v1"
OUTCOME_REWARD_PROFILE_V2_SMALL_DECIMAL = "outcome_v2_small_decimal"

EXPLORATION_EPSILON_GREEDY_FIXED = "epsilon_greedy_fixed"
EXPLORATION_CATEGORICAL_POLICY_SAMPLING = "categorical_policy_sampling"

RL_ALPHA = env_float("CGDQN_RL_ALPHA", 0.001)
RL_GAMMA = env_float("CGDQN_RL_GAMMA", 0.9)
RL_EPSILON = env_float("CGDQN_RL_EPSILON", 0.1)
RL_MAX_EPOCHS = env_int("CGDQN_RL_MAX_EPOCHS", 30)

DDQN_TARGET_UPDATE_STEPS = env_int("CGDQN_DDQN_TARGET_UPDATE_STEPS", 100)
TARGET_UPDATE_MODE = (
    os.environ.get("CGDQN_TARGET_UPDATE_MODE", "hard").strip().lower() or "hard"
)

VALUE_TD_LOSS_MSE = "mse"
VALUE_TD_LOSS_SMOOTH_L1 = "smooth_l1"
VALUE_TD_LOSS = (
    os.environ.get("CGDQN_VALUE_TD_LOSS", VALUE_TD_LOSS_SMOOTH_L1).strip().lower()
    or VALUE_TD_LOSS_SMOOTH_L1
)
SMOOTH_L1_BETA = env_float("CGDQN_SMOOTH_L1_BETA", 1.0)

REPLAY_ENABLED = env_bool("CGDQN_REPLAY_ENABLED", False)
REPLAY_CAPACITY = env_int("CGDQN_REPLAY_CAPACITY", 20000)
REPLAY_BATCH_SIZE = env_int("CGDQN_REPLAY_BATCH_SIZE", 64)
REPLAY_WARMUP_TRANSITIONS = env_int("CGDQN_REPLAY_WARMUP_TRANSITIONS", 512)
REPLAY_WARMUP_EPOCHS = env_int("CGDQN_REPLAY_WARMUP_EPOCHS", 3)
REPLAY_UPDATES_PER_STEP = env_int("CGDQN_REPLAY_UPDATES_PER_STEP", 1)
REPLAY_SAMPLE_POLICY = (
    os.environ.get("CGDQN_REPLAY_SAMPLE_POLICY", "uniform").strip().lower() or "uniform"
)

ACTION_PRIOR_BETA = env_float("CGDQN_ACTION_PRIOR_BETA", 0.05)

PPO_CLIP_EPS = env_float("CGDQN_PPO_CLIP_EPS", 0.2)
PPO_VALUE_COEF = env_float("CGDQN_PPO_VALUE_COEF", 0.5)
PPO_ENTROPY_COEF = env_float("CGDQN_PPO_ENTROPY_COEF", 0.01)

OUTCOME_REWARD_RSRP_WEIGHT = env_float("CGDQN_OUTCOME_REWARD_RSRP_WEIGHT", 0.45)
OUTCOME_REWARD_SINR_WEIGHT = env_float("CGDQN_OUTCOME_REWARD_SINR_WEIGHT", 0.30)
OUTCOME_REWARD_EXEC_WEIGHT = env_float("CGDQN_OUTCOME_REWARD_EXEC_WEIGHT", 0.15)
OUTCOME_REWARD_PPHO_WEIGHT = env_float("CGDQN_OUTCOME_REWARD_PPHO_WEIGHT", 0.10)
OUTCOME_REWARD_RSRP_SCALE_DB = env_float("CGDQN_OUTCOME_REWARD_RSRP_SCALE_DB", 6.0)
OUTCOME_REWARD_CLIP_MIN = env_float("CGDQN_OUTCOME_REWARD_CLIP_MIN", -1.0)
OUTCOME_REWARD_CLIP_MAX = env_float("CGDQN_OUTCOME_REWARD_CLIP_MAX", 1.0)
OUTCOME_REWARD_PROFILE = (
    os.environ.get("CGDQN_OUTCOME_REWARD_PROFILE", OUTCOME_REWARD_PROFILE_V1)
    or OUTCOME_REWARD_PROFILE_V1
)

OUTCOME_V2_RSRP_SCALE = env_float("CGDQN_OUTCOME_V2_RSRP_SCALE", 0.10)
OUTCOME_V2_SINR_OUTAGE_PENALTY = env_float("CGDQN_OUTCOME_V2_SINR_OUTAGE_PENALTY", -0.10)
OUTCOME_V2_EXEC_GOOD_REWARD = env_float("CGDQN_OUTCOME_V2_EXEC_GOOD_REWARD", 0.03)
OUTCOME_V2_EXEC_RLF_PENALTY = env_float("CGDQN_OUTCOME_V2_EXEC_RLF_PENALTY", -0.05)
OUTCOME_V2_EXEC_NEG_GAIN_PENALTY = env_float("CGDQN_OUTCOME_V2_EXEC_NEG_GAIN_PENALTY", -0.03)
OUTCOME_V2_PPHO_PENALTY = env_float("CGDQN_OUTCOME_V2_PPHO_PENALTY", -0.10)
OUTCOME_V2_CLIP_MIN = env_float("CGDQN_OUTCOME_V2_CLIP_MIN", -0.30)
OUTCOME_V2_CLIP_MAX = env_float("CGDQN_OUTCOME_V2_CLIP_MAX", 0.20)


def reward_weights_snapshot() -> dict[str, float]:
    return {
        "rsrp": OUTCOME_REWARD_RSRP_WEIGHT,
        "sinr": OUTCOME_REWARD_SINR_WEIGHT,
        "execution": OUTCOME_REWARD_EXEC_WEIGHT,
        "ppho": OUTCOME_REWARD_PPHO_WEIGHT,
        "rsrp_scale_db": OUTCOME_REWARD_RSRP_SCALE_DB,
        "clip_min": OUTCOME_REWARD_CLIP_MIN,
        "clip_max": OUTCOME_REWARD_CLIP_MAX,
        "profile": OUTCOME_REWARD_PROFILE,
        "v2_rsrp_scale": OUTCOME_V2_RSRP_SCALE,
        "v2_sinr_outage_penalty": OUTCOME_V2_SINR_OUTAGE_PENALTY,
        "v2_exec_good_reward": OUTCOME_V2_EXEC_GOOD_REWARD,
        "v2_exec_rlf_penalty": OUTCOME_V2_EXEC_RLF_PENALTY,
        "v2_exec_neg_gain_penalty": OUTCOME_V2_EXEC_NEG_GAIN_PENALTY,
        "v2_ppho_penalty": OUTCOME_V2_PPHO_PENALTY,
        "v2_clip_min": OUTCOME_V2_CLIP_MIN,
        "v2_clip_max": OUTCOME_V2_CLIP_MAX,
    }
